apiVersion: skaffold/v3
kind: Config
metadata:
  name: sbgcrun-frontend
deploy:
  cloudrun: {}
profiles:
  - name: v1
    activation:
      - env: DEPLOY_ENV=v1
    manifests:
      rawYaml:
        - ./cloudrun.yaml
